### PR TITLE
Release v1.0.0 🎉

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose

Officially release v1.0.0!

There hasn't been much movement here in a while, but convergences are actively used by interactors and the new BigTest CLI. I think we're good to finally release v1.0.0!

## Approach

- Update to all stable dependencies.
- Removed deprecated `once` method.
- Update changelog and package.json for release.

### Todo:

- [x] We might wanna tackle #15 before this release. Or maybe temporarily remove the types for now so we at least don't ship with incorrect or broken definitions.

### CODE REVIEW

**Comment by Robdel12** [comment]
Hm, I think we should update the typescript defs before cutting 1.0. If we really don't wanna do that we could remove them, but I don't really like that too much haha.

**Comment by cowboyd** [comment]
Agree. Is it possible to test typescript integration?

**Comment by wwilsman** [comment]
https://www.npmjs.com/package/typescript-definition-tester

Looks like there isn't really a way without just writing stuff in typescript

**Comment by wwilsman** [comment]
So @Robdel12 and I had a conversation about this, and I think we should just remove the typescript support for now (as I see he has already done). I spent some time learning typescript and attempting to update the files without knowing if it was truly correct, but then thought about what this would mean for the rest of BigTest.

If typescript is a requirement for `1.0.0` for this package, it should be for other BigTest packages as well. Which is much more time consuming than simply updating the defs here. Especially when none of us maintaining the packages use typescript to be able to tell if the definitions are even correct.

I think typescript support can come later in a proper minor version. And we can also make sure that we release typescript support for all BigTest packages so that there are no inconsistencies between them when using more than a one.

**Comment by wwilsman** [comment]
@Robdel12 I re-ordered the commits so that the typescripts are not included in the release commit. Even though CI would just release this whole branch, that might be a little confusing when looking through commit history.

Oh, and I'll need an approving review

**Review by Robdel12 — APPROVED** [review]
:shipit:

**Pull request merged**
